name: QMK build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile my keyboard
        run: qmk compile -kb skyloong/gk61 -km default

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.hex
            *.bin
            *.uf2
